# -*- coding: utf-8 -*-
"""mallcustomer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mpkSxSZ1xNVIiPvaXE7YpD5t7Gl__i7E

# EDA on Mall Customers
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

df = pd.read_csv("C:\\Users\\user\\Downloads\\Mall_Customers.csv")

df.head()

df.info()

df.describe()

df.isnull().sum()

# Gender distribution
df['Gender'].value_counts()

# Average Age
df['Age'].mean()

# Average Spending Score
df['Spending Score (1-100)'].mean()

# Gender count
sns.countplot(x='Gender', data=df)
plt.show()

# Age distribution
sns.histplot(df['Age'], bins=10, kde=True)
plt.show()

# Spending Score distribution
sns.histplot(df['Spending Score (1-100)'], bins=10, kde=True)
plt.show()

# Age vs Spending Score
sns.scatterplot(x='Age', y='Spending Score (1-100)', hue='Gender', data=df)
plt.show()

